const byId = (id) => document.getElementById(id);
const challengeSelect = byId("challenge"), editor = byId("editor"), runButton = byId("run"), runtimeStatus = byId("runtimeStatus");
let worker, runtimeReady = false, runTimer;
function currentChallenge(){return window.PYTHON_CHALLENGES.find((item)=>item.id===challengeSelect.value)}
function storageKey(challenge){return "inference-lab-solution:"+challenge.id}
function format(value){return JSON.stringify(value)}
function escapeHtml(value){const node=document.createElement("div");node.textContent=String(value);return node.innerHTML}
function clearResults(){byId("summary").className="summary muted";byId("summary").textContent="Run your solution when Python is ready.";byId("results").innerHTML="";byId("stdoutWrap").hidden=true}
function showChallenge(){const c=currentChallenge();byId("title").textContent=c.title;byId("prompt").textContent=c.prompt;byId("difficulty").textContent=c.difficulty;byId("concepts").innerHTML=c.concepts.map((x)=>'<span class="chip">'+x+"</span>").join("");byId("hints").innerHTML=c.hints.map((x)=>"<li>"+x+"</li>").join("");byId("visibleTests").innerHTML=c.visibleTests.map((t,i)=>"<pre>Test "+(i+1)+": "+t.label+"\ninputs: "+format(t.args)+"\nexpected: "+(t.expectedException||format(t.expected))+"</pre>").join("");editor.value=localStorage.getItem(storageKey(c))||c.starterCode;clearResults()}
function setRuntime(state,message){runtimeStatus.className="status "+state;runtimeStatus.querySelector("span").textContent=message;runtimeReady=state==="ready";runButton.disabled=!runtimeReady}
function startWorker(){setRuntime("","Loading Python runtime…");worker=new Worker("runner-worker.js");worker.onmessage=handleWorkerMessage;worker.onerror=(event)=>{setRuntime("error","Runtime error");byId("summary").className="summary fail-text";byId("summary").textContent=event.message||"Python worker could not start."};worker.postMessage({type:"initialize"})}
function renderResults(payload){if(payload.compileError){byId("summary").className="summary fail-text";byId("summary").textContent="Your solution could not be loaded.";byId("results").innerHTML='<div class="test fail"><strong>Python error</strong><pre>'+escapeHtml(payload.compileError)+"</pre></div>";return}const passed=payload.results.filter((x)=>x.passed).length,total=payload.results.length;byId("summary").className="summary "+(passed===total?"pass-text":"fail-text");byId("summary").textContent=passed===total?"All "+total+" tests passed.":passed+" of "+total+" tests passed.";byId("results").innerHTML=payload.results.map((r)=>{const expected=r.expectedException||format(r.expected),actual=r.actualException||format(r.actual),visibility=r.hidden?"Hidden test":"Visible test",detail=r.passed?"":"<pre>inputs: "+escapeHtml(format(r.args))+"\nexpected: "+escapeHtml(expected)+"\nactual: "+escapeHtml(actual)+(r.message?"\n\n"+escapeHtml(r.message):"")+"</pre>";return '<div class="test '+(r.passed?"pass":"fail")+'"><strong>'+(r.passed?"✓ ":"✗ ")+visibility+": "+escapeHtml(r.label)+"</strong>"+detail+"</div>"}).join("");if(payload.stdout){byId("stdoutWrap").hidden=false;byId("stdout").textContent=payload.stdout}}
function handleWorkerMessage(event){const m=event.data;if(m.type==="ready"){setRuntime("ready","Python ready");return}if(m.type==="fatal"){clearTimeout(runTimer);setRuntime("error","Runtime failed");byId("summary").className="summary fail-text";byId("summary").textContent=m.message;return}if(m.type==="result"){clearTimeout(runTimer);runButton.disabled=false;renderResults(m.payload)}}
function runTests(){if(!runtimeReady)return;const c=currentChallenge();localStorage.setItem(storageKey(c),editor.value);runButton.disabled=true;byId("summary").className="summary muted";byId("summary").textContent="Running tests…";byId("results").innerHTML="";const tests=c.visibleTests.map((t)=>Object.assign({hidden:false},t)).concat(c.hiddenTests.map((t)=>Object.assign({hidden:true},t)));worker.postMessage({type:"run",code:editor.value,functionName:c.functionName,tests:tests});runTimer=setTimeout(()=>{worker.terminate();byId("summary").className="summary fail-text";byId("summary").textContent="Execution exceeded 5 seconds and was stopped. Check for an infinite loop.";startWorker()},5000)}
window.PYTHON_CHALLENGES.forEach((c)=>{const option=document.createElement("option");option.value=c.id;option.textContent=c.title;challengeSelect.appendChild(option)});
challengeSelect.onchange=showChallenge;editor.addEventListener("input",()=>localStorage.setItem(storageKey(currentChallenge()),editor.value));editor.addEventListener("keydown",(event)=>{if(event.key==="Tab"){event.preventDefault();const start=editor.selectionStart;editor.value=editor.value.slice(0,start)+"    "+editor.value.slice(editor.selectionEnd);editor.selectionStart=editor.selectionEnd=start+4}if((event.metaKey||event.ctrlKey)&&event.key==="Enter")runTests()});runButton.onclick=runTests;byId("reset").onclick=()=>{const c=currentChallenge();editor.value=c.starterCode;localStorage.removeItem(storageKey(c));clearResults()};byId("clear").onclick=clearResults;showChallenge();startWorker();
